### PR TITLE
fix: Apply allocation filters before aggregation to ensure AND operator order independence

### LINKED ISSUE #3371: v2 filter parameter AND("+") operator doesn't work
**Describe the bug**
I am trying v2 filters on the /allocation API. The **OR** operator "|" seems to work as described but the **AND** "+" is not. Looks like the "+" is simply ignored because i can get different responses with filter=A+B vs filter=B+A

**To Reproduce**
1. `GET /allocation?window=yesterday&aggregate=namespace&filter=namespace:"ns1"&accumulate=true&shareIdle=true"` This returns stuff in ns1 namespace
2. `GET /allocation?window=yesterday&aggregate=namespace&filter=namespace:"ns1"+cluster:"a-non-existent-kube-system-ns-uuid"&accumulate=true&shareIdle=true"` this return EXACTLY the same response as the one you got in step 1. note the value of cluster field filter is a uuid that doesn't exist, shouldn't this be returning no data?
3. `GET /allocation?window=yesterday&aggregate=namespace&filter=cluster:"a-non-existent-kube-system-ns-uuid"+namespace:"ns1"&accumulate=true&shareIdle=true"` this returns no data, as expected.

**Expected behavior**
step 2 and 3 should return no data. Basically, the AND operator is respected.

**Which version of OpenCost are you using?**
1.117.2

**Additional context**
K8s v1.33.2

### PR DESCRIPTION
**Pull request by spa-raj**
## What does this PR change?
* The AND operator (+) in v2 allocation filters was order-dependent, causing filters like `namespace:"ns1"+cluster:"non-existent"` to behave differently than `cluster:"non-existent"+namespace:"ns1"`.

* Root cause: Aggregation was happening before filtering, which could merge or lose allocation properties (like cluster), making them unavailable for filter matching. This caused the first filter condition to match while subsequent conditions had incomplete data.

* Solution: Reordered operations to filter -> aggregate -> accumulate. Filtering now happens on individual allocations with all properties intact, ensuring consistent AND behavior regardless of filter order. 

## Does this PR relate to any other PRs?
* No

## How will this PR impact users?
*  Users experiencing incorrect results with AND filters (+) in v2 allocation API will now get correct behavior. Previously, filters like namespace:"ns1"+cluster:"non-existent" could incorrectly return data, while reversing the order would correctly return nothing. 
* After this fix, AND filters work consistently regardless of order - both conditions must match for allocations to be included. Users who may have worked around this bug by ordering their filters specifically will need to update their queries.

## Does this PR address any GitHub or Zendesk issues?
* Fixes #3371 

## How was this PR tested?
* Added unit test Test_AllocationFilterAnd_OrderIndependence in core/pkg/opencost/allocationfilter_test.go:745-820 that validates:
  - AND filters produce identical results regardless of filter order
  - The specific bug scenario (namespace matches, cluster doesn't) correctly returns false
  - Both matching conditions return true
  - All allocation properties remain available for filtering before aggregation

## Does this PR require changes to documentation?
* No

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
* This should be labeled for next release but I don't have the access to label it.

### CODE REVIEW

File: pkg/costmodel/aggregation.go [hunk 1]
```diff
@@ -227,7 +227,11 @@ func (a *Accesses) ComputeAllocationHandler(w http.ResponseWriter, r *http.Reque
 	// Get allocation filter if provided
 	allocationFilter := qp.Get("filter", "")
 
-	asr, err := a.Model.QueryAllocation(window, step, aggregateBy, includeIdle, idleByNode, includeProportionalAssetResourceCosts, includeAggregatedMetadata, sharedLoadBalancer, accumulateBy, shareIdle)
+	// Query allocations WITHOUT aggregation/accumulation first, so we can filter
+	// on individual allocations before they are aggregated. This ensures filters
+	// can match on all allocation properties (like cluster, node, etc.) before
+	// they are potentially lost or merged during aggregation.
+	asr, err := a.Model.QueryAllocation(window, step, nil, includeIdle, idleByNode, includeProportionalAssetResourceCosts, includeAggregatedMetadata, sharedLoadBalancer, opencost.AccumulateOptionNone, shareIdle)
```
Comment (ameijer) [inline pkg/costmodel/aggregation.go]: wow. yeah. the fact that we don't even pass in the filter here is a red flag. Your approach is right, I just wanted to ask why not do this in the QueryAllocation method, instead of further down this method? Just asking, not demanding that we do that

Comment (spa-raj) [reply pkg/costmodel/aggregation.go]: I kept it in the handler to avoid changing the core method signature, but you are right that's the wrong trade-off. I'm already duplicating the same filtering logic in both handlers,  and we're doing unnecessary work (computing idle allocations for stuff we just filter out anyway).

I should add a filter string param to QueryAllocation and do the filtering there before aggregation. Existing callers can just pass "".

Want me to refactor it that way?

Comment (ameijer) [reply pkg/costmodel/aggregation.go]: yes let's do that!

**Review by ameijer — APPROVED** [review]
