### PR TITLE
Handle SUSE Rancher node special case

### LINKED ISSUE #2029: Incorrect cpu ram and gpu hourly cost on GPU nodes
**Describe the bug**
CPU RAM and GPU hourly cost metrics are much lower than they should be when a node has a GPU present. Found this issue in kubecost but also tested with opencost and we are seeing the same result.
See https://github.com/kubecost/cost-analyzer-helm-chart/issues/2418

This is in a Suse Rancher cluster where each node has the same `instance_type` of `rke2` which from the kubecost/opencost logs is not known and so pricing falls back to defaults. Specifying custom default prices exhibits the same unexpected behavior. Hourly costs reflect the expect cost values based on the custom pricing only when there is no gpu on the node. When the gpu is present the values are divided by a significant factor that seems related to the sum of the three prices.

Our guess is kubecost/opencost is doing something like summing the resource costs into a single machine cost but then unnecessarily dividing each cost by that total.

**To Reproduce**
See the kubecost issue https://github.com/kubecost/cost-analyzer-helm-chart/issues/2418 but install opencost instead of kubecost.

**Expected behavior**
GPU nodes should have hourly costs that match the specified prices.

**Screenshots**
E.g. from grafana, three nodes without gpu and one node with gpu, all using fallback default prices
image

**Which version of OpenCost are you using?**
1.105.0-rc.6 (b7736a7)

**Additional context**
Cluster is a Suse Rancher RKE2 cluster running on AWS EC2. GPU node in this instance is a `g4dn.xlarge` with one Nvidia Tesla T4 GPU.

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR change?
* Adds a special case for SUSE Rancher in AWS, to skip ratio math that was adjusting instance pricing, courtesy of all SUSE Rancher nodes showing as "rke2", and thus forcing default pricing.
* **An important note** The draft PR currently includes a commit with replication code. The PR must not be merged until that commit is picked out. If it's not picked out, it will break opencost for anyone else. That's why this is a draft. I've left that commit in for now to enable others to test these changes, once people are happy, it can get picked out and we can move on.

## Does this PR relate to any other PRs?
* I sure hope not.

## How will this PR impact users?
* Enables expected default pricing behavior for SUSE Rancher users

## Does this PR address any GitHub or Zendesk issues?
* Closes #2029 , and [BURNDOWN-222](https://kubecost.atlassian.net/browse/BURNDOWN-222)

## How was this PR tested?
* Locally, and in a dev cluster. **BUT**, and this is an important caveat, this was tested by deliberately overriding node details on a code level, to force the "rke2" instance type without having to actually spend money on GPU nodes. Ideally we'd like to see this also replicated in a real SUSE Rancher environ.

## Does this PR require changes to documentation?
* I don't think so? Probably?

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
* Sure would if I could. Seriously, why can't I add labels?

### CODE REVIEW

**Comment by ian-lmcb** [comment]
Hi @CampfireRemnants, saw this pop up on my notifications per the reference to #2029.

I am wondering if there's a misinterpretation here as it sounds like the direction you're going is to fix rke2 instance pricing to use aws pricing which doesn't sound right to me (or sounds like an entire feature on its own, to detect and provide ec2 pricing for suserancher running on ec2). When we found this issue we were using SuseRancher in AWS to emulate a customer environment that uses SuseRancher on a VMware cluster and so it was intended and expected that custom pricing would be used for the cluster.

In our example we're seeing correctly the custom prices on rke2 instances without a gpu. Then on instances with a gpu all the prices go out of whack. So it sounds like there's a pricing issue for instances with gpu when custom prices are used, rather than an issue specific to suserancher or aws.

Possibly I may be misunderstanding the PR description

**Comment by ghost** [comment]
@ian-lmcb So, this PR does still use the custom default prices, it pulls them from the config same as before; what we believe is happening here, is that because the instance type `rke2` isn't recognized by the costmodel (since it's not a "real" AWS instance type), it then falls into a backup flow for inferring pricing from the defaults, and the GPU count/CPU core count/RAM bytes reported by the Kubernetes API. That in turn has a lot of calculations  of ratios, etc. to modify those prices, and that's what seemed to be modifying the costs you were seeing emitted by a consistent ratio. What this does is skip over those ratio calculations that were throwing the reported numbers off when the instance type would indicate a SUSE Rancher cluster. Does that clarify the changes we made?

File: pkg/costmodel/aggregation.go [hunk 1]
```diff
@@ -2275,15 +2275,15 @@ func (a *Accesses) ComputeAllocationHandler(w http.ResponseWriter, r *http.Reque
 	// Otherwise it is computed at the cluster level. (Not relevant if idle
 	// is not included.)
 	idleByNode := qp.GetBool("idleByNode", false)
-	sharedLoadBalancer := qp.GetBool("sharelb", false)
+	// sharedLoadBalancer := qp.GetBool("sharelb", false)
```
Comment (AjayTripathy) [inline pkg/costmodel/aggregation.go]: what's going on here? Why are we removing the shared loadbalancer functionality for a special case?

Comment (ghost) [reply pkg/costmodel/aggregation.go]: Ah, thanks for the catch here--I believe that had been broken when this was first worked on, and got disabled back then so that it would run

Comment (AjayTripathy) [reply pkg/costmodel/aggregation.go]: Has that been fixed and these changes can be reverted?

**Comment by cliffcolvin** [comment]
@CampfireRemnants can you take a look at Ajay's question above and we can make sure its resolved. Also we'll need to make sure and sign the commit for DCO to pass.

**Comment by ghost** [comment]
The replication code that was being used to simulate a GPU environment has been picked back out--if anyone wanted to try running it themselves but hasn't gotten the chance yet, you should be able to pick it back in; This also took out the changes to run when the shared loadbalancer had been broken.

**Review by AjayTripathy — APPROVED** [review]

**Review by teevans — APPROVED** [review]

**Comment by ian-lmcb** [comment]
Hi @CampfireRemnants, @AjayTripathy, I just want to let you know we're testing a suserancher environment that is running on a VMware vSphere data center and the node instance types we see here are not `rke2` but instead strings along the lines of `vsphere-vm.cpu-2.mem-4gb.os-ubuntu`.

So I reckon this fix will not work in this situation since the fix is applied only to instance type `rke2`.

I'm also confused about why the code is taking ratios in the first place when the default prices are already specified. I guess perhaps I misunderstand how the `defaultModelPricing` values are meant to be used. E.g. are the values not already per cpu, per unit of ram, per gpu prices?

The only documentation I've found for `defaultModelPricing` is in the example values.yaml here https://github.com/kubecost/cost-analyzer-helm-chart/blob/44428e49ed6acaab8fda180792db1f9bde436e11/cost-analyzer/values.yaml#L1339C143-L1339C143.

I would have thought that if I put in say 1.0 for the cpu cost then `node_cpu_hourly_cost` would become something like 1.0/730 = 0.00137 (using 730 hours per month) per cpu.

Looking back at #2029 it looks like I didn't see that for either the gpu and no-gpu node cases.

Is there documentation on how `defaultModelPricing` is meant to be used?

**Comment by AjayTripathy** [comment]
If we detect that you're on a cloud provider, the default prices are used to generate ratios on splitting up node cost into constituent resource costs. If not, as should be the case in vSphere, we use those resource prices defined in defaultModelPricing directly. Are you seeing something different?
