### PR TITLE
Change Azure billing API from GET to POST method

### LINKED ISSUE #3326: Using GET http method instead of POST for azure billing account pricing
**Describe the bug**
Azure API for getting pricing from billing account has wrong http method configured.
ENDPOINT: `https://management.azure.com/providers/Microsoft.Billing/billingAccounts/{Billing_account_id}/billingPeriods/202508/providers/Microsoft.Consumption/pricesheets/download?api-version=2022-06-01&ln=en`

This is using GET http method here, https://github.com/opencost/opencost/blob/b576f5595e085c13d8ab80b5a67a952d9da36573/pkg/cloud/azure/pricesheetclient.go#L114 but it should use POST. 

We are getting this error

```
<html>
<body>
<!--StartFragment-->
"message": "Invalid billing period 202508 (Request ID: )" |  
-- | --
  |   | 2025-08-22 12:03:41.418 | "code": "404", |  
  |   | 2025-08-22 12:03:41.418 | "error": { |  
  |   | 2025-08-22 12:03:41.418 | { |  
  |   | 2025-08-22 12:03:41.418 | -------------------------------------------------------------------------------- |  
  |   | 2025-08-22 12:03:41.418 | ERROR CODE: 404 |  
  |   | 2025-08-22 12:03:41.418 | RESPONSE 404: 404 Not Found |  
  |   | 2025-08-22 12:03:41.418 | -------------------------------------------------------------------------------- |  
  |   | 2025-08-22 12:03:41.418 | 2025-08-22T10:03:41.418673376Z ERR Error downloading Azure price sheet: getting download URL: beginning pricesheet download: GET https://management.azure.com/providers/Microsoft.Billing/billingAccounts/{billing_account_id}/billingPeriods/202508/providers/Microsoft.Consumption/pricesheets/download
<!--EndFragment-->
</body>
</html>
```
**To Reproduce**
1. Configure the azure custom pricing by using these two env variables 
```
opencost:
  exporter:
    extraEnv:
      AZURE_BILLING_ACCOUNT: <your billing account id>
      AZURE_OFFER_ID: <your offer id>
```

You would get the error which is mentioned above. I tried the same endpoint locally with POST method and i got the valid response. So we need to change `GET` to `POST` here https://github.com/opencost/opencost/blob/b576f5595e085c13d8ab80b5a67a952d9da36573/pkg/cloud/azure/pricesheetclient.go#L114

**Expected behavior**
It should be able to download the pricing from the billing account at the end. 
**Screenshots**

**Which version of OpenCost are you using?**
You can find the version from the container's startup logging or from the bottom of the page in the UI.

**Additional context**
Using opencost v116.0

### PR DESCRIPTION
**Pull request by fromsaurav**
## Summary
Fixes the Azure billing account pricing API to use the correct HTTP method (POST instead of GET), resolving 404 errors when downloading price sheets.

## Changes
- Changed `http.MethodGet` to `http.MethodPost` in `pkg/cloud/azure/pricesheetclient.go:114`
- Added comprehensive tests in `pkg/cloud/azure/pricesheetclient_test.go`

## Testing
Validation of the fix:
```bash
# Verify compilation
go build ./pkg/cloud/azure/...

# Run Azure package tests
go test ./pkg/cloud/azure/... -v
```

Before: API calls failed with 404 "Invalid billing period" errors when using AZURE_BILLING_ACCOUNT and AZURE_OFFER_ID configuration.
After: Price sheet downloads work correctly with the proper POST method as required by Azure's API.

Fixes [#3326](https://github.com/opencost/opencost/issues/3326#issue-3345123330)

### CODE REVIEW

File: pkg/cloud/azure/pricesheetclient.go [hunk 1]
```diff
@@ -111,7 +111,7 @@ func (client *PriceSheetClient) downloadByBillingPeriodCreateRequest(ctx context
 		return nil, errors.New("parameter billingPeriodName cannot be empty")
 	}
 	urlPath := fmt.Sprintf(downloadByBillingPeriodTemplate, url.PathEscape(client.billingAccountID), url.PathEscape(billingPeriodName))
-	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.host, urlPath))
+	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.host, urlPath))
```
Comment (avrodrigues5) [inline pkg/cloud/azure/pricesheetclient.go:114]: This looks ok

API [doc](https://learn.microsoft.com/en-us/rest/api/cost-management/price-sheet/download-by-billing-account?view=rest-cost-management-2025-03-01&viewFallbackFrom=rest-cost-management-2022-05-01&utm_source=chatgpt.com&tabs=HTTP) states its a  POST. Not sure why this initial code was a GET method.

**Comment by avrodrigues5** [comment]
@fromsaurav Please update the branch, Will approve the PR after that!

CC: @ameijer

**Comment by fromsaurav** [comment]
@avrodrigues5 done!

**Review by ameijer — APPROVED** [review]
approving as per @avrodrigues5 's recommendation

**Review by avrodrigues5 — APPROVED** [review]
