### PR TITLE
fix(mcp): Add nil checks to prevent panic in cloud cost transformation

### LINKED ISSUE #3502: fix(mcp): Add nil checks to prevent panic in cloud cost transformation
**Describe the bug**
The `transformCloudCostSetRange` function in the MCP server dereferences `Window.Start()` and `Window.End()` pointers without nil checks, which can panic and crash the entire MCP server when cloud providers return malformed window data.

**To Reproduce**
1. Enable MCP server with cloud cost integration (`ENABLE_MCP_SERVER=true`)
2. Configure a cloud provider (AWS, GCP, Azure, etc.)
3. Query cloud costs via MCP when provider returns incomplete time window data
4. Observe MCP server panic with nil pointer dereference

**Location**
- **File:** `pkg/mcp/server.go`

**Current Code:**

```
Window: &TimeWindow{
    Start: *ccSet.Window.Start(),  // Panic if nil!
    End:   *ccSet.Window.End(),    // Panic if nil!
} 
```

**Expected behavior**
Check for nil windows/timestamps, log warning, and skip malformed data instead of crashing. Proposed Fix:

```
if ccSet.Window == nil || ccSet.Window.Start() == nil || ccSet.Window.End() == nil {
    log.Warnf("Skipping cloud cost set with invalid window")
    continue
}
```

**Which version of OpenCost are you using?**
Current develop branch

### PR DESCRIPTION
**Pull request by vtushar06**
## Description

Adds comprehensive nil pointer checks in the `transformCloudCostSetRange` function to prevent panic crashes when cloud providers return malformed window data. The function now safely handles nil `Window.Start()` and `Window.End()` pointers for both **CloudCostSet** and individual **CloudCost** items, logging warnings and skipping invalid data instead of crashing the MCP server.

## Related Issues

Fixes #3502

## User Impact

No breaking changes. This is a defensive fix that improves MCP server stability:

**Before**: MCP server would panic and crash when receiving malformed cloud cost data with nil window timestamps
**After**: Server logs warnings and gracefully skips invalid data, continuing to process valid cloud costs
Fully backward compatible - valid data processing unchanged

## Testing

Unit Tests:

Added `TestTransformCloudCostSetRange_NilPointerHandling `covering 6 critical scenarios:

- Nil CloudCostSetRange
- Nil CloudCostSet in slice
- Nil [Window.Start()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) and [Window.End()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) on CloudCostSet
- Nil [Window.Start()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) and [Window.End()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) on CloudCost items
- Mixed valid/invalid data to ensure graceful handling

All MCP package tests pass: go test ./pkg/mcp 

Integration Tests:
The integration test failures in the original PR #3503 are pre-existing infrastructure issues unrelated to this fix, as this change only affects the MCP package's nil pointer handling logic.

---

> [!NOTE]
> Prevents panics in `transformCloudCostSetRange` by skipping/logging nil or invalid windows for sets/items and adds targeted unit tests.
> 
> - **MCP Backend**:
>   - **Cloud cost transform**: In `transformCloudCostSetRange`, skip and log when encountering:
>     - `nil` `CloudCostSet`
>     - `CloudCostSet.Window` with `nil` `Start` or `End`
>     - `nil` `CloudCost` items or items with `nil` `Window.Start`/`End`
>   - **Stability**: Add `nil` guard in Kubernetes percent averaging loop.
> - **Tests**:
>   - Add `TestTransformCloudCostSetRange_NilPointerHandling` covering `nil` range, `nil` set, `nil` window bounds, invalid item windows, and mixed valid/invalid items.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 61af74736fe3ddae7830389b160aac63bc5801d7. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by vtushar06** [comment]
Hi @ameijer, can you please look into this, if this suits the core problem we can move either with this as I tried to focus on main tests and core issue

**Comment by ameijer** [comment]
bugbot review

File: pkg/mcp/server.go [hunk 1]
```diff
@@ -947,10 +961,21 @@ func transformCloudCostSetRange(ccsr *opencost.CloudCostSetRange) *CloudCostResp
 	var avgKubernetesPercent float64
 	var numerator, denominator float64
 	for _, ccSet := range ccsr.CloudCostSets {
+		if ccSet == nil {
+			continue
+		}
+		// Skip sets with invalid windows (consistent with first loop)
+		if ccSet.Window.Start() == nil || ccSet.Window.End() == nil {
```
Comment (ameijer) [inline pkg/mcp/server.go:969]: warn

File: pkg/mcp/server.go [hunk 2]
```diff
@@ -947,10 +961,21 @@ func transformCloudCostSetRange(ccsr *opencost.CloudCostSetRange) *CloudCostResp
...
+			continue
+		}
 		for _, item := range ccSet.CloudCosts {
 			if item == nil {
 				continue
 			}
+			// Skip items with invalid windows (consistent with first loop)
+			if item.Window.Start() == nil || item.Window.End() == nil {
```
Comment (ameijer) [inline pkg/mcp/server.go:979]: warn

File: pkg/mcp/server.go [hunk 3]
```diff
@@ -947,10 +961,21 @@ func transformCloudCostSetRange(ccsr *opencost.CloudCostSetRange) *CloudCostResp
 	var avgKubernetesPercent float64
 	var numerator, denominator float64
 	for _, ccSet := range ccsr.CloudCostSets {
+		if ccSet == nil {
```
Comment (ameijer) [inline pkg/mcp/server.go:964]: warn

File: pkg/mcp/server.go [hunk 4]
```diff
@@ -885,6 +892,13 @@ func transformCloudCostSetRange(ccsr *opencost.CloudCostSetRange) *CloudCostResp
 		// Convert each cloud cost item
 		for _, item := range ccSet.CloudCosts {
 			if item == nil {
+				log.Warnf("transformCloudCostSetRange: skipping nil CloudCost item in set %s", setName)
+				continue
+			}
+
+			// Check for nil Window or nil Start/End pointers on the item
+			if item.Window.Start() == nil || item.Window.End() == nil {
+				log.Warnf("transformCloudCostSetRange: skipping CloudCost item with invalid window (nil start or end) in set %s", setName)
```
Comment (ameijer) [inline pkg/mcp/server.go]: consider printing both the start and end in all these logs to help troubleshoot, even if at least one of them will be nil, maybe the other one has a date that will clue in to the bad range

**Comment by ameijer** [comment]
@vtushar06 what is your opinion on the latest copilot review?

**Comment by vtushar06** [comment]
Thanks for the review but I think this suggestion is not applicable here as`Window` type is a struct value (not a pointer), defined as:

```
go
type Window struct {
    start *time.Time
    end   *time.Time
}
```
In Go,we cannot compare struct values to nil - only pointers can be nil. The current code correctly checks if the Start() and End() methods return nil pointers, which is the appropriate validation for this type.

File: pkg/mcp/server.go [hunk 5]
```diff
@@ -868,6 +868,13 @@ func transformCloudCostSetRange(ccsr *opencost.CloudCostSetRange) *CloudCostResp
 	// Process each cloud cost set in the range
 	for i, ccSet := range ccsr.CloudCostSets {
 		if ccSet == nil {
+			log.Warnf("transformCloudCostSetRange: skipping nil CloudCostSet at index %d", i)
+			continue
+		}
+
+		// Check for nil Window or nil Start/End pointers before dereferencing
+		if ccSet.Window.Start() == nil || ccSet.Window.End() == nil {
```
[the remark this answers is not in the document]
Comment (vtushar06) [reply pkg/mcp/server.go:876]: explaining why the suggestions don't apply

**Review by ameijer — APPROVED** [review]
LGTM. thanks for your continued contributions, @vtushar06
