### PR TITLE
Correctly calculate `gpuCost` when the `"nvidia.com/gpu.replicas"` label is present.

### LINKED ISSUE #2657: gpuCost computation error
**Describe the bug**
gpuCost in /costDataModel is not computed correctly.

**To Reproduce**
I'm using g5.2xlarge instance on AWS with nvidia GPU operator v23.9.1.
Hourly instance cost is 1.3529600000

Specs:
```
{
   "memory":"32 GiB",
   "vcpu":"8",
   "gpu":"1"
}
```

Node has the following status.capacity:
```
apiVersion: v1
kind: Node
status:
  capacity:
    cpu: '8'
    memory: 32500272Ki
    nvidia.com/gpu: '1'
```

and the following labels:
```
apiVersion: v1
kind: Node
metadata:
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: g5.2xlarge
    beta.kubernetes.io/os: linux
    feature.node.kubernetes.io/cpu-cpuid.ADX: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AESNI: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX2: 'true'
    feature.node.kubernetes.io/cpu-cpuid.CLZERO: 'true'
    feature.node.kubernetes.io/cpu-cpuid.CMPXCHG8: 'true'
    feature.node.kubernetes.io/cpu-cpuid.FMA3: 'true'
    feature.node.kubernetes.io/cpu-cpuid.FP256: 'true'
    feature.node.kubernetes.io/cpu-cpuid.FXSR: 'true'
    feature.node.kubernetes.io/cpu-cpuid.FXSROPT: 'true'
    feature.node.kubernetes.io/cpu-cpuid.HYPERVISOR: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IBPB: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IBRS: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IBRS_PREFERRED: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IBRS_PROVIDES_SMP: 'true'
    feature.node.kubernetes.io/cpu-cpuid.LAHF: 'true'
    feature.node.kubernetes.io/cpu-cpuid.MCOMMIT: 'true'
    feature.node.kubernetes.io/cpu-cpuid.MOVBE: 'true'
    feature.node.kubernetes.io/cpu-cpuid.MOVU: 'true'
    feature.node.kubernetes.io/cpu-cpuid.OSXSAVE: 'true'
    feature.node.kubernetes.io/cpu-cpuid.RDPRU: 'true'
    feature.node.kubernetes.io/cpu-cpuid.SHA: 'true'
    feature.node.kubernetes.io/cpu-cpuid.SPEC_CTRL_SSBD: 'true'
    feature.node.kubernetes.io/cpu-cpuid.SSE4A: 'true'
    feature.node.kubernetes.io/cpu-cpuid.STIBP: 'true'
    feature.node.kubernetes.io/cpu-cpuid.SYSCALL: 'true'
    feature.node.kubernetes.io/cpu-cpuid.SYSEE: 'true'
    feature.node.kubernetes.io/cpu-cpuid.TOPEXT: 'true'
    feature.node.kubernetes.io/cpu-cpuid.WBNOINVD: 'true'
    feature.node.kubernetes.io/cpu-cpuid.X87: 'true'
    feature.node.kubernetes.io/cpu-cpuid.XGETBV1: 'true'
    feature.node.kubernetes.io/cpu-cpuid.XSAVE: 'true'
    feature.node.kubernetes.io/cpu-cpuid.XSAVEC: 'true'
    feature.node.kubernetes.io/cpu-cpuid.XSAVEOPT: 'true'
    feature.node.kubernetes.io/cpu-hardware_multithreading: 'true'
    feature.node.kubernetes.io/cpu-model.family: '23'
    feature.node.kubernetes.io/cpu-model.id: '49'
    feature.node.kubernetes.io/cpu-model.vendor_id: AMD
    feature.node.kubernetes.io/kernel-config.NO_HZ: 'true'
    feature.node.kubernetes.io/kernel-config.NO_HZ_IDLE: 'true'
    feature.node.kubernetes.io/kernel-version.full: 5.15.0-1045-aws
    feature.node.kubernetes.io/kernel-version.major: '5'
    feature.node.kubernetes.io/kernel-version.minor: '15'
    feature.node.kubernetes.io/kernel-version.revision: '0'
    feature.node.kubernetes.io/pci-10de.present: 'true'
    feature.node.kubernetes.io/pci-1d0f.present: 'true'
    feature.node.kubernetes.io/storage-nonrotationaldisk: 'true'
    feature.node.kubernetes.io/system-os_release.ID: ubuntu
    feature.node.kubernetes.io/system-os_release.VERSION_ID: '20.04'
    feature.node.kubernetes.io/system-os_release.VERSION_ID.major: '20'
    feature.node.kubernetes.io/system-os_release.VERSION_ID.minor: '04'
    gpu-g5-2xlarge: 'true'
    k8s.amazonaws.com/accelerator: nvidia-a10g
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: g5.2xlarge
    nvidia.com/cuda.driver.major: '535'
    nvidia.com/cuda.driver.minor: '129'
    nvidia.com/cuda.driver.rev: '03'
    nvidia.com/cuda.runtime.major: '12'
    nvidia.com/cuda.runtime.minor: '2'
    nvidia.com/gfd.timestamp: '1709634570'
    nvidia.com/gpu.compute.major: '8'
    nvidia.com/gpu.compute.minor: '6'
    nvidia.com/gpu.count: '1'
    nvidia.com/gpu.deploy.container-toolkit: 'true'
    nvidia.com/gpu.deploy.dcgm: 'true'
    nvidia.com/gpu.deploy.dcgm-exporter: 'true'
    nvidia.com/gpu.deploy.device-plugin: 'true'
    nvidia.com/gpu.deploy.driver: 'true'
    nvidia.com/gpu.deploy.gpu-feature-discovery: 'true'
    nvidia.com/gpu.deploy.node-status-exporter: 'true'
    nvidia.com/gpu.deploy.nvsm: ''
    nvidia.com/gpu.deploy.operator-validator: 'true'
    nvidia.com/gpu.family: ampere
    nvidia.com/gpu.machine: g5.2xlarge
    nvidia.com/gpu.memory: '23028'
    nvidia.com/gpu.present: 'true'
    nvidia.com/gpu.product: NVIDIA-A10G
    nvidia.com/gpu.replicas: '1'
    nvidia.com/mig.capable: 'false'
    nvidia.com/mig.strategy: single
```

The default.json (cost model ratio) are the following:
```
{
   "CPU":"0.031611",
   "RAM":"0.004237",
   "GPU":"0.95"
}
```

/costDataModel is giving:
```
{
   "hourlyCost":"1.3529600000",
   "CPU":"8",
   "CPUHourlyCost":"0.111315",
   "RAM":"32 GiB",
   "RAMBytes":"33280282624.000000",
   "RAMGBHourlyCost":"0.014920",
   "storage":"1 x 450 GB NVMe SSD",
   "storageHourlyCost":"",
   "usesDefaultPrice":false,
   "baseCPUPrice":"0.031611",
   "baseRAMPrice":"0.004237",
   "baseGPUPrice":"0.95",
   "usageType":"ondemand",
   "gpu":"1",
   "gpuName":"",
   "gpuCost":"3.345316",
   "vgpu":"1",
   "instanceType":"g5.2xlarge",
   "region":"eu-west-1",
   "providerID":"aws:///eu-west-1a/i-xxxxxx",
   "archType":"amd64"
}
```

**Expected behavior**
gpuCost is 3.345316 (greater than the instance cost) instead of 0.96028296.

**Potential solution**
GPU cost is computed in this part: https://github.com/opencost/opencost/blob/v1.109.0/pkg/costmodel/costmodel.go#L1172
According to the cost I get it acts as gpuc is 0.
It seems that given the node labels, we enter in this case: https://github.com/opencost/opencost/blob/v1.109.0/pkg/costmodel/costmodel.go#L1087 and gpuc is never set.
Adding `gpuc = float64(q.Value())` at https://github.com/opencost/opencost/blob/v1.109.0/pkg/costmodel/costmodel.go#L1098 does solve the problem.

**Which version of OpenCost are you using?**
v1.109.0

**Additional context**
Add any other context about the problem here. Kubernetes versions and which public clouds you are working with are especially important.

### PR DESCRIPTION
**Pull request by thomasvn**
## What does this PR change?

* First and foremost, this PR aims to fix https://github.com/opencost/opencost/issues/2657. The issue is caused by the fact that the `GetNodeCost()` function uses this variable `gpuc` to represent gpu count. Previously, there was one location where the `gpuc` variable was not being set and remaining as its default 0 ([code ref](https://github.com/opencost/opencost/blob/6a1ad9a3662d9cabb9a630b97724a382909e2bd3/pkg/costmodel/costmodel.go#L1098)).
* This PR fixes the issue described above, which is a one liner. But also adds additional accuracy in the case where `hasReplicas=true` and in the scenarios of either 1) GFD configured `renameByDefault=true` or 2) GFD configured `renameByDefault=false`
* This PR also breaks out the GPU parsing logic into its own function for enhanced readability and unit testability. 

## Does this PR relate to any other PRs?
* Supersedes https://github.com/opencost/opencost/pull/2658. This current PR has additional accuracy, is a full refactor, and is targeted to merge into `develop`.

## How will this PR impact users?
* As titled

## Does this PR address any GitHub or Zendesk issues?
* Fixes https://github.com/opencost/opencost/issues/2657

## How was this PR tested?

Tested against a `g4dn.xlarge`. One with sharing, and one without.

<details>
<summary> g4dn.xlarge no sharing </summary>

```yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    alpha.kubernetes.io/provided-node-ip: 192.168.90.222
    csi.volume.kubernetes.io/nodeid: '{"ebs.csi.aws.com":"i-09ccc0461b6e636a6"}'
    nfd.node.kubernetes.io/feature-labels: cpu-cpuid.ADX,cpu-cpuid.AESNI,cpu-cpuid.AVX,cpu-cpuid.AVX2,cpu-cpuid.AVX512BW,cpu-cpuid.AVX512CD,cpu-cpuid.AVX512DQ,cpu-cpuid.AVX512F,cpu-cpuid.AVX512VL,cpu-cpuid.AVX512VNNI,cpu-cpuid.CMPXCHG8,cpu-cpuid.FMA3,cpu-cpuid.FXSR,cpu-cpuid.FXSROPT,cpu-cpuid.HYPERVISOR,cpu-cpuid.LAHF,cpu-cpuid.MOVBE,cpu-cpuid.MPX,cpu-cpuid.OSXSAVE,cpu-cpuid.SYSCALL,cpu-cpuid.SYSEE,cpu-cpuid.X87,cpu-cpuid.XGETBV1,cpu-cpuid.XSAVE,cpu-cpuid.XSAVEC,cpu-cpuid.XSAVEOPT,cpu-cpuid.XSAVES,cpu-hardware_multithreading,cpu-model.family,cpu-model.id,cpu-model.vendor_id,kernel-config.NO_HZ,kernel-config.NO_HZ_IDLE,kernel-version.full,kernel-version.major,kernel-version.minor,kernel-version.revision,nvidia.com/cuda.driver-version.full,nvidia.com/cuda.driver-version.major,nvidia.com/cuda.driver-version.minor,nvidia.com/cuda.driver-version.revision,nvidia.com/cuda.driver.major,nvidia.com/cuda.driver.minor,nvidia.com/cuda.driver.rev,nvidia.com/cuda.runtime-version.full,nvidia.com/cuda.runtime-version.major,nvidia.com/cuda.runtime-version.minor,nvidia.com/cuda.runtime.major,nvidia.com/cuda.runtime.minor,nvidia.com/gfd.timestamp,nvidia.com/gpu.compute.major,nvidia.com/gpu.compute.minor,nvidia.com/gpu.count,nvidia.com/gpu.family,nvidia.com/gpu.machine,nvidia.com/gpu.memory,nvidia.com/gpu.mode,nvidia.com/gpu.product,nvidia.com/gpu.replicas,nvidia.com/gpu.sharing-strategy,nvidia.com/mig.capable,nvidia.com/mps.capable,nvidia.com/vgpu.present,pci-10de.present,pci-1d0f.present,storage-nonrotationaldisk,system-os_release.ID,system-os_release.VERSION_ID,system-os_release.VERSION_ID.major
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2024-08-04T17:07:16Z"
  labels:
    alpha.eksctl.io/cluster-name: qa-eks3
    alpha.eksctl.io/nodegroup-name: spot-gpu-small
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: g4dn.xlarge
    beta.kubernetes.io/os: linux
    eks.amazonaws.com/capacityType: SPOT
    eks.amazonaws.com/nodegroup: spot-gpu-small
    eks.amazonaws.com/nodegroup-image: ami-0b1185307c5ce352c
    eks.amazonaws.com/sourceLaunchTemplateId: lt-07dd83bd9973fa066
    eks.amazonaws.com/sourceLaunchTemplateVersion: "1"
    failure-domain.beta.kubernetes.io/region: us-east-2
    failure-domain.beta.kubernetes.io/zone: us-east-2a
    feature.node.kubernetes.io/cpu-cpuid.ADX: "true"
    feature.node.kubernetes.io/cpu-cpuid.AESNI: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX2: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512BW: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512CD: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512DQ: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512F: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512VL: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI: "true"
    feature.node.kubernetes.io/cpu-cpuid.CMPXCHG8: "true"
    feature.node.kubernetes.io/cpu-cpuid.FMA3: "true"
    feature.node.kubernetes.io/cpu-cpuid.FXSR: "true"
    feature.node.kubernetes.io/cpu-cpuid.FXSROPT: "true"
    feature.node.kubernetes.io/cpu-cpuid.HYPERVISOR: "true"
    feature.node.kubernetes.io/cpu-cpuid.LAHF: "true"
    feature.node.kubernetes.io/cpu-cpuid.MOVBE: "true"
    feature.node.kubernetes.io/cpu-cpuid.MPX: "true"
    feature.node.kubernetes.io/cpu-cpuid.OSXSAVE: "true"
    feature.node.kubernetes.io/cpu-cpuid.SYSCALL: "true"
    feature.node.kubernetes.io/cpu-cpuid.SYSEE: "true"
    feature.node.kubernetes.io/cpu-cpuid.X87: "true"
    feature.node.kubernetes.io/cpu-cpuid.XGETBV1: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVE: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVEC: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVEOPT: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVES: "true"
    feature.node.kubernetes.io/cpu-hardware_multithreading: "true"
    feature.node.kubernetes.io/cpu-model.family: "6"
    feature.node.kubernetes.io/cpu-model.id: "85"
    feature.node.kubernetes.io/cpu-model.vendor_id: Intel
    feature.node.kubernetes.io/kernel-config.NO_HZ: "true"
    feature.node.kubernetes.io/kernel-config.NO_HZ_IDLE: "true"
    feature.node.kubernetes.io/kernel-version.full: 5.10.219-208.866.amzn2.x86_64
    feature.node.kubernetes.io/kernel-version.major: "5"
    feature.node.kubernetes.io/kernel-version.minor: "10"
    feature.node.kubernetes.io/kernel-version.revision: "219"
    feature.node.kubernetes.io/pci-10de.present: "true"
    feature.node.kubernetes.io/pci-1d0f.present: "true"
    feature.node.kubernetes.io/storage-nonrotationaldisk: "true"
    feature.node.kubernetes.io/system-os_release.ID: amzn
    feature.node.kubernetes.io/system-os_release.VERSION_ID: "2"
    feature.node.kubernetes.io/system-os_release.VERSION_ID.major: "2"
    k8s.io/cloud-provider-aws: 659b6cdec8c90e1f2729fd59c20d9a9d
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ip-192-168-90-222.us-east-2.compute.internal
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: g4dn.xlarge
    nvidia.com/cuda.driver-version.full: 535.183.01
    nvidia.com/cuda.driver-version.major: "535"
    nvidia.com/cuda.driver-version.minor: "183"
    nvidia.com/cuda.driver-version.revision: "01"
    nvidia.com/cuda.driver.major: "535"
    nvidia.com/cuda.driver.minor: "183"
    nvidia.com/cuda.driver.rev: "01"
    nvidia.com/cuda.runtime-version.full: "12.2"
    nvidia.com/cuda.runtime-version.major: "12"
    nvidia.com/cuda.runtime-version.minor: "2"
    nvidia.com/cuda.runtime.major: "12"
    nvidia.com/cuda.runtime.minor: "2"
    nvidia.com/gfd.timestamp: "1722791304"
    nvidia.com/gpu.compute.major: "7"
    nvidia.com/gpu.compute.minor: "5"
    nvidia.com/gpu.count: "1"
    nvidia.com/gpu.family: turing
    nvidia.com/gpu.machine: g4dn.xlarge
    nvidia.com/gpu.memory: "15360"
    nvidia.com/gpu.mode: compute
    nvidia.com/gpu.product: Tesla-T4
    nvidia.com/gpu.replicas: "1"
    nvidia.com/gpu.sharing-strategy: none
    nvidia.com/mig.capable: "false"
    nvidia.com/mps.capable: "false"
    nvidia.com/vgpu.present: "false"
    owner: qa
    topology.ebs.csi.aws.com/zone: us-east-2a
    topology.kubernetes.io/region: us-east-2
    topology.kubernetes.io/zone: us-east-2a
  name: ip-192-168-90-222.us-east-2.compute.internal
  resourceVersion: "34660748"
  uid: 6b0aa5f9-c1c1-43f3-8ab9-4f99ec2aad50
spec:
  providerID: aws:///us-east-2a/i-09ccc0461b6e636a6
status:
  allocatable:
    cpu: 3920m
    ephemeral-storage: "76224326324"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 15378876Ki
    nvidia.com/gpu: "1"
    pods: "29"
  capacity:
    cpu: "4"
    ephemeral-storage: 83873772Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 16069052Ki
    nvidia.com/gpu: "1"
    pods: "29"
```
</details>

<details>
<summary> g4dn.xlarge with sharing </summary>

```yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    alpha.kubernetes.io/provided-node-ip: 192.168.94.8
    csi.volume.kubernetes.io/nodeid: '{"ebs.csi.aws.com":"i-099385ff7a3ad7939"}'
    nfd.node.kubernetes.io/feature-labels: cpu-cpuid.ADX,cpu-cpuid.AESNI,cpu-cpuid.AVX,cpu-cpuid.AVX2,cpu-cpuid.AVX512BW,cpu-cpuid.AVX512CD,cpu-cpuid.AVX512DQ,cpu-cpuid.AVX512F,cpu-cpuid.AVX512VL,cpu-cpuid.AVX512VNNI,cpu-cpuid.CMPXCHG8,cpu-cpuid.FMA3,cpu-cpuid.FXSR,cpu-cpuid.FXSROPT,cpu-cpuid.HYPERVISOR,cpu-cpuid.LAHF,cpu-cpuid.MOVBE,cpu-cpuid.MPX,cpu-cpuid.OSXSAVE,cpu-cpuid.SYSCALL,cpu-cpuid.SYSEE,cpu-cpuid.X87,cpu-cpuid.XGETBV1,cpu-cpuid.XSAVE,cpu-cpuid.XSAVEC,cpu-cpuid.XSAVEOPT,cpu-cpuid.XSAVES,cpu-hardware_multithreading,cpu-model.family,cpu-model.id,cpu-model.vendor_id,kernel-config.NO_HZ,kernel-config.NO_HZ_IDLE,kernel-version.full,kernel-version.major,kernel-version.minor,kernel-version.revision,nvidia.com/cuda.driver-version.full,nvidia.com/cuda.driver-version.major,nvidia.com/cuda.driver-version.minor,nvidia.com/cuda.driver-version.revision,nvidia.com/cuda.driver.major,nvidia.com/cuda.driver.minor,nvidia.com/cuda.driver.rev,nvidia.com/cuda.runtime-version.full,nvidia.com/cuda.runtime-version.major,nvidia.com/cuda.runtime-version.minor,nvidia.com/cuda.runtime.major,nvidia.com/cuda.runtime.minor,nvidia.com/gfd.timestamp,nvidia.com/gpu.compute.major,nvidia.com/gpu.compute.minor,nvidia.com/gpu.count,nvidia.com/gpu.family,nvidia.com/gpu.machine,nvidia.com/gpu.memory,nvidia.com/gpu.mode,nvidia.com/gpu.product,nvidia.com/gpu.replicas,nvidia.com/gpu.sharing-strategy,nvidia.com/mig.capable,nvidia.com/mps.capable,nvidia.com/vgpu.present,pci-10de.present,pci-1d0f.present,storage-nonrotationaldisk,system-os_release.ID,system-os_release.VERSION_ID,system-os_release.VERSION_ID.major
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2024-07-09T18:51:35Z"
  labels:
    alpha.eksctl.io/cluster-name: qa-eks3
    alpha.eksctl.io/nodegroup-name: gpu-small
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: g4dn.xlarge
    beta.kubernetes.io/os: linux
    eks.amazonaws.com/capacityType: ON_DEMAND
    eks.amazonaws.com/nodegroup: gpu-small
    eks.amazonaws.com/nodegroup-image: ami-0b1185307c5ce352c
    eks.amazonaws.com/sourceLaunchTemplateId: lt-025af968da23148a3
    eks.amazonaws.com/sourceLaunchTemplateVersion: "1"
    failure-domain.beta.kubernetes.io/region: us-east-2
    failure-domain.beta.kubernetes.io/zone: us-east-2a
    feature.node.kubernetes.io/cpu-cpuid.ADX: "true"
    feature.node.kubernetes.io/cpu-cpuid.AESNI: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX2: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512BW: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512CD: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512DQ: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512F: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512VL: "true"
    feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI: "true"
    feature.node.kubernetes.io/cpu-cpuid.CMPXCHG8: "true"
    feature.node.kubernetes.io/cpu-cpuid.FMA3: "true"
    feature.node.kubernetes.io/cpu-cpuid.FXSR: "true"
    feature.node.kubernetes.io/cpu-cpuid.FXSROPT: "true"
    feature.node.kubernetes.io/cpu-cpuid.HYPERVISOR: "true"
    feature.node.kubernetes.io/cpu-cpuid.LAHF: "true"
    feature.node.kubernetes.io/cpu-cpuid.MOVBE: "true"
    feature.node.kubernetes.io/cpu-cpuid.MPX: "true"
    feature.node.kubernetes.io/cpu-cpuid.OSXSAVE: "true"
    feature.node.kubernetes.io/cpu-cpuid.SYSCALL: "true"
    feature.node.kubernetes.io/cpu-cpuid.SYSEE: "true"
    feature.node.kubernetes.io/cpu-cpuid.X87: "true"
    feature.node.kubernetes.io/cpu-cpuid.XGETBV1: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVE: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVEC: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVEOPT: "true"
    feature.node.kubernetes.io/cpu-cpuid.XSAVES: "true"
    feature.node.kubernetes.io/cpu-hardware_multithreading: "true"
    feature.node.kubernetes.io/cpu-model.family: "6"
    feature.node.kubernetes.io/cpu-model.id: "85"
    feature.node.kubernetes.io/cpu-model.vendor_id: Intel
    feature.node.kubernetes.io/kernel-config.NO_HZ: "true"
    feature.node.kubernetes.io/kernel-config.NO_HZ_IDLE: "true"
    feature.node.kubernetes.io/kernel-version.full: 5.10.219-208.866.amzn2.x86_64
    feature.node.kubernetes.io/kernel-version.major: "5"
    feature.node.kubernetes.io/kernel-version.minor: "10"
    feature.node.kubernetes.io/kernel-version.revision: "219"
    feature.node.kubernetes.io/pci-10de.present: "true"
    feature.node.kubernetes.io/pci-1d0f.present: "true"
    feature.node.kubernetes.io/storage-nonrotationaldisk: "true"
    feature.node.kubernetes.io/system-os_release.ID: amzn
    feature.node.kubernetes.io/system-os_release.VERSION_ID: "2"
    feature.node.kubernetes.io/system-os_release.VERSION_ID.major: "2"
    k8s.io/cloud-provider-aws: 659b6cdec8c90e1f2729fd59c20d9a9d
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ip-192-168-94-8.us-east-2.compute.internal
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: g4dn.xlarge
    nvidia.com/cuda.driver-version.full: 535.183.01
    nvidia.com/cuda.driver-version.major: "535"
    nvidia.com/cuda.driver-version.minor: "183"
    nvidia.com/cuda.driver-version.revision: "01"
    nvidia.com/cuda.driver.major: "535"
    nvidia.com/cuda.driver.minor: "183"
    nvidia.com/cuda.driver.rev: "01"
    nvidia.com/cuda.runtime-version.full: "12.2"
    nvidia.com/cuda.runtime-version.major: "12"
    nvidia.com/cuda.runtime-version.minor: "2"
    nvidia.com/cuda.runtime.major: "12"
    nvidia.com/cuda.runtime.minor: "2"
    nvidia.com/device-plugin.config: test-sharing
    nvidia.com/gfd.timestamp: "1721913931"
    nvidia.com/gpu.compute.major: "7"
    nvidia.com/gpu.compute.minor: "5"
    nvidia.com/gpu.count: "1"
    nvidia.com/gpu.family: turing
    nvidia.com/gpu.machine: g4dn.xlarge
    nvidia.com/gpu.memory: "15360"
    nvidia.com/gpu.mode: compute
    nvidia.com/gpu.product: Tesla-T4
    nvidia.com/gpu.replicas: "4"
    nvidia.com/gpu.sharing-strategy: time-slicing
    nvidia.com/mig.capable: "false"
    nvidia.com/mps.capable: "false"
    nvidia.com/vgpu.present: "false"
    owner: qa
    topology.ebs.csi.aws.com/zone: us-east-2a
    topology.kubernetes.io/region: us-east-2
    topology.kubernetes.io/zone: us-east-2a
  name: ip-192-168-94-8.us-east-2.compute.internal
  resourceVersion: "34660062"
  uid: 36caae5a-ca14-453c-a607-e6bbb9ac5087
spec:
  providerID: aws:///us-east-2a/i-099385ff7a3ad7939
status:
  allocatable:
    cpu: 3920m
    ephemeral-storage: "76224326324"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 15378876Ki
    nvidia.com/gpu: "0"
    nvidia.com/gpu.shared: "4"
    pods: "29"
  capacity:
    cpu: "4"
    ephemeral-storage: 83873772Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 16069052Ki
    nvidia.com/gpu: "0"
    nvidia.com/gpu.shared: "4"
    pods: "29"
```
</details>

Ran OpenCost locally then hit `http://localhost:9003/costDataModel` and saw the following result for a pod running on a GPU node:

```json
"node": {
  "hourlyCost": "0.5260000000",
  "CPU": "4",
  "CPUHourlyCost": "0.010603",
  "RAM": "16 GiB",
  "RAMBytes": "16454709248.000000",
  "RAMGBHourlyCost": "0.001421",
  "storage": "125 GB NVMe SSD",
  "storageHourlyCost": "",
  "usesDefaultPrice": false,
  "baseCPUPrice": "0.021811",
  "baseRAMPrice": "0.002923",
  "baseGPUPrice": "0.95",
  "usageType": "preemptible",
  "gpu": "1",
  "gpuName": "",
  "gpuCost": "0.461814",
  "vgpu": "1",
  "instanceType": "g4dn.xlarge",
  "region": "us-east-2",
  "providerID": "aws:///us-east-2a/i-09ccc0461b6e636a6",
  "archType": "amd64"
},
```

In the above response, `CPUHourlyCost * CPU + RAMGBHourlyCost * RAM + gpuCost * gpu == hourlyCost`. This fixes the immediate issue described in https://github.com/opencost/opencost/issues/2657.

Regarding the Kubecost Assets API, this PR fixes an overestimation in the hourly rate of certain GPU nodes. An example of a [g4dn.xlarge node](https://aws.amazon.com/ec2/instance-types/g4/) ($0.526/hr) shown below.

Before:

Before

After:

After

## Does this PR require changes to documentation?
* N/A

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
* v2.4

### CODE REVIEW

File: pkg/costmodel/costmodel.go [hunk 1]
```diff
@@ -1075,27 +1075,38 @@ func (cm *CostModel) GetNodeCost(cp costAnalyzerCloud.Provider) (map[string]*cos
...
-			if gpuCount != 0 {
-				newCnode.GPU = fmt.Sprintf("%d", gpuCount)
-				newCnode.VGPU = newCnode.GPU
-				gpuc = float64(gpuCount)
-			}
-		} else if hasReplicas { // See https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-sharing.html
-			if q.Value() == 0 {
-				q = n.Status.Capacity["nvidia.com/gpu.shared"]
-			}
+		if ok && gpuCount != 0 && !hasReplicas {
```
Comment (ameijer) [inline pkg/costmodel/costmodel.go]: @thomasvn is there any way I can convince you to break out all this GPU logic into another function? Then you could write a quick unit test

Comment (ameijer) [reply pkg/costmodel/costmodel.go]: this function is uber large as is and could use the love

Comment (thomasvn) [reply pkg/costmodel/costmodel.go]: @ameijer Yep good callout! Let's use this as an opportunity to break it out into another function and unit test.

File: pkg/costmodel/costmodel.go [hunk 2]
```diff
@@ -1075,27 +1075,38 @@ func (cm *CostModel) GetNodeCost(cp costAnalyzerCloud.Provider) (map[string]*cos
...
 			if ok {
 				newCnode.GPU = g
+				gpuc, err = strconv.ParseFloat(g, 64)
+				if err != nil {
+					log.Warnf("Could not parse label \"nvidia.com/gpu.count\": \"%s\". Setting to 0.", g)
+					gpuc = 0.0
+				}
 			} else {
-				newCnode.GPU = fmt.Sprintf("%d", 0)
+				log.Warnf("Could not find label \"nvidia.com/gpu.count\". Setting to 0.")
```
Comment (nikovacevic) [inline pkg/costmodel/costmodel.go]: We now have a warning here, but seem to have removed the line setting to `0`. Is that intentional?

**Review by nikovacevic — COMMENTED** [review]
Second Alex's comment. Just one other small question.

File: pkg/costmodel/costmodel.go [hunk 3]
```diff
@@ -1075,27 +1075,38 @@ func (cm *CostModel) GetNodeCost(cp costAnalyzerCloud.Provider) (map[string]*cos
...
-			if q.Value() == 0 {
-				q = n.Status.Capacity["nvidia.com/gpu.shared"]
-			}
+		if ok && gpuCount != 0 && !hasReplicas {
+			newCnode.GPU = fmt.Sprintf("%d", gpuCount)
+			newCnode.VGPU = newCnode.GPU
+			gpuc = float64(gpuCount)
+		} else if hasReplicas {
+			// Special case. The "nvidia.com/gpu.replicas" label is usually
+			// applied by NVIDIA's GPU Operator or GPU Feature Discovery pod.
```
Comment (chipzoller) [inline pkg/costmodel/costmodel.go]: It's always applied by GFD. The operator may optionally deploy GFD but it is (now) otherwise deployed through the device plugin.

**Review by chipzoller — COMMENTED** [review]
Additionally, just making sure (for code comments, etc) that we understand `nvidia.com/gpu.replicas` applies to sharing strategies of time-slicing and MPS, not exclusively the former.

File: pkg/costmodel/costmodel.go (hunk 3 above)
Comment (thomasvn) [reply pkg/costmodel/costmodel.go]: Comment is updated! Marking as resolved.

File: pkg/costmodel/costmodel.go (hunk 2 above)
Comment (thomasvn) [reply pkg/costmodel/costmodel.go]: Good callout! This was fixed in my full refactor recently. Marking as resolved!

File: pkg/costmodel/costmodel.go (hunk 1 above)
Comment (thomasvn) [reply pkg/costmodel/costmodel.go]: Committed my refactor + unit tests. Marking as resolved for now.

File: pkg/costmodel/costmodel.go [hunk 4]
```diff
@@ -1070,48 +1063,24 @@ func (cm *CostModel) GetNodeCost(cp costAnalyzerCloud.Provider) (map[string]*cos
...
-			}
-		} else {
-			gpuc, err = strconv.ParseFloat(newCnode.GPU, 64)
-			if err != nil {
-				gpuc = 0.0
-			}
+		// The k8s API will often report more accurate results for GPU count
+		// than cloud provider public pricing APIs. If found, override the
+		// original value.
+		gpuOverride, vgpuOverride, err := getGPUCount(cm.Cache, n)
```
Comment (ameijer) [inline pkg/costmodel/costmodel.go:1074]: this reads very nicely 👏

File: pkg/costmodel/costmodel.go [hunk 5]
```diff
@@ -2358,6 +2327,68 @@ func getStatefulSetsOfPod(pod v1.Pod) []string {
 	return []string{}
 }
 
+// getGPUCount leverages the k8s API to identify the number of GPUs and vGPUs on
+// the node.
+func getGPUCount(cache clustercache.ClusterCache, n *v1.Node) (*float64, *float64, error) {
```
Comment (ameijer) [inline pkg/costmodel/costmodel.go]: nitpicky, and an optional suggestion - pointers to primitives aren't my favorite. To me reading this with limited familiarity, what does a nil GPU count mean? an error in processing? something with no GPU overrides? 

I would return a negative number here if nothing could be found - that clearly identifies it as bogus and can be discarded. 

Again, personal opinion here and open to push back

File: pkg/costmodel/costmodel_test.go [hunk 6]
```diff
@@ -4,8 +4,99 @@ import (
...
+		},
+		{
+			name: "No GPU",
+			node: &v1.Node{
+				Status: v1.NodeStatus{
+					Capacity: v1.ResourceList{},
+				},
+			},
+			expectedGPU:  nil,
+			expectedVGPU: nil,
```
Comment (ameijer) [inline pkg/costmodel/costmodel_test.go]: these tests are very enlightening, thank you. would you consider adding a case for aws VGPU so I can see what you are expecting there?

File: pkg/costmodel/costmodel.go (hunk 5 above)
Comment (thomasvn) [reply pkg/costmodel/costmodel.go]: In this case a nil GPU count means that when parsing the node's metadata/labels we could not find a GPU count, which is valid if the node is not equipped with a GPU to begin with.

I'll go ahead and update the comments here above the function signature to make that clear. I'm also open to returning `-1` as opposed to `nil`, whichever you think is more clear and better practice. Lmk what you think still!

File: pkg/costmodel/costmodel_test.go (hunk 6 above)
Comment (thomasvn) [reply pkg/costmodel/costmodel_test.go]: Will do! For testing the AWS VGPU case I'll need to create more mocks.

File: pkg/costmodel/costmodel.go (hunk 5 above)
Comment (thomasvn) [reply pkg/costmodel/costmodel.go]: Ok I've updated so that the function returns `-1` as opposed to `nil` when no GPU could be identified. I've also updated the function comments! Lmk what you think.

File: pkg/costmodel/costmodel_test.go (hunk 6 above)
Comment (thomasvn) [reply pkg/costmodel/costmodel_test.go]: @ameijer Actually I'm going to hold from implementing tests for the AWS vGPU. It's not clear to me whether it's still widely used within this repo https://github.com/awslabs/aws-virtual-gpu-device-plugin. I also don't have much experience in this. Are you ok if we revisit this at a later point? cc @chipzoller

Comment (chipzoller) [reply pkg/costmodel/costmodel_test.go]: Skip AWS vGPU as no one is using it any more.

**Review by chipzoller — COMMENTED** [review]
Great PR, @thomasvn! Really appreciate the thoroughness here. I can't speak to the Go but the scenarios addressed, before, and after look good. I'll have to defer to others but would like to get this in ASAP and then test.

**Review by ameijer — APPROVED** [review]
LGTM, @thomasvn LMK when you are ready for this to get merged

**Comment by thomasvn** [comment]
@ameijer Ready for merge! I'm also going to cherry-pick into v2.4 branch afterwards.
