### PR TITLE
Fix: CSV export data query failures with missing metrics

### LINKED ISSUE #3073: CSV export erroring out
**Describe the bug**
OpenCost is configured to export CSV automatically. Initially it was configured to a Google Bucket but now I switched to a local path to see if that was the issue. It was not.

**To Reproduce**
1. Deploy OpenCost via helm with the following values (trimmed out unrelated values):
```
opencost:
  exporter:
    csv_path: /mnt/export/export.csv
    persistence:
      accessMode: ReadWriteOnce
      enabled: true
      size: 10Gi
      storageClass: ceph-block
```
2. Verify that pod has correct variable:
```
spec:
  containers:
  - env:
    - name: EXPORT_CSV_FILE
      value: /mnt/export/export.csv
```
3. Following error occurs:
```
2025-03-14T16:44:04.839759534Z INF Starting CSV exporter worker...
2025-03-14T16:44:06.092901369Z ERR Error updating CSV: no data
```

**Expected behavior**
CSV is generated

**Screenshots**

**Which version of OpenCost are you using?**
1.113.0

**Additional context**
Data is properly shown in the UI, even downloading a CSV from the UI works.
When configured with a cloud export location (in this case, google buckets), the following errors are observed:
```
2025-03-13T19:40:55.748098657Z INF Starting CSV exporter worker...
2025-03-13T19:40:55.961488394Z ERR Error updating CSV: querying oldest sample: no results
2025-03-14T00:10:00.026979163Z ERR Error updating CSV: no data
```

### PR DESCRIPTION
**Pull request by fromsaurav**
### Issues Fixed
- **CSV Export Failures:** Fixed "no data" and "querying oldest sample: no results" errors
- **Hard Dependencies:** Removed dependency on `node_cpu_hourly_cost` metric for CSV export

### Changes
- Added fallback logic in `QueryDataCoverage` when primary metric unavailable (1-day time range)
- Implemented graceful date skipping in CSV export instead of complete failure
- Enhanced logging with warning messages for troubleshooting

### Testing Results
**Build Success:**
```bash
$ go build ./cmd/costmodel && echo "Build status: $?"
Build status: 0
```

**Implementation Verification:**
```bash
$ grep -c "skipping this date" pkg/costmodel/csv_export.go
1
$ grep -c "1 day ago" modules/prometheus-source/pkg/prom/metricsquerier.go  
1
```

### Before/After
**Before:** `ERR Error updating CSV: no data`
**After:** `WARN QueryDataCoverage: using fallback time range` + CSV export continues

Fixes [#3073](https://github.com/opencost/opencost/issues/3073)

### CODE REVIEW

File: modules/prometheus-source/pkg/prom/metricsquerier.go [hunk 1]
```diff
@@ -1474,7 +1474,15 @@ func (pds *PrometheusMetricsQuerier) QueryDataCoverage(limitDays int) (time.Time
...
-		return time.Time{}, time.Time{}, fmt.Errorf("querying oldest sample: %w", err)
+		// If node_cpu_hourly_cost metric is not available, fallback to a reasonable time range
+		// This prevents CSV export from failing when the metric doesn't exist yet
+		log.Warnf("QueryDataCoverage: node_cpu_hourly_cost metric not available, using fallback time range")
+		
+		// Use a reasonable fallback: start from 1 day ago to account for metric collection delay
+		fallbackEnd := time.Now().UTC().Truncate(timeutil.Day)
+		fallbackStart := fallbackEnd.AddDate(0, 0, -1) // 1 day ago
+		
+		return fallbackStart, fallbackEnd, nil
```
Comment (ameijer) [inline modules/prometheus-source/pkg/prom/metricsquerier.go:1811]: can you also match this in the collector source?

Comment (tusharbisht02) [reply modules/prometheus-source/pkg/prom/metricsquerier.go:1811]: @ameijer   
ERR Error updating CSV: no data 

Facing same issue @fromsaurav can you add these recommended changes

**Comment by fromsaurav** [comment]
@tusharbisht02 sure, i'll add the changes!

File: modules/prometheus-source/pkg/prom/metricsquerier.go (hunk 1 above)
Comment (tusharbisht02) [reply modules/prometheus-source/pkg/prom/metricsquerier.go:1811]: Please suggest if there any temporary fix for this @fromsaurav

**Comment by tusharbisht02** [comment]
@fromsaurav Any updates on this we are in need of this functionality.

**Review by ameijer — APPROVED** [review]

**Comment by fromsaurav** [comment]
@tusharbisht02 done!
